// lib/strings.dart
class AppStrings {
  // Uygulamada kullandığımız metin anahtarları (search, notifications, home, vs.)

  static Map<String, String> tr = {
    'search': 'Arama',
    'notifications': 'Bildirimler',
    'home': 'Anasayfa',
    'messages': 'Mesajlar',
    'profile': 'Profil',
    'languageSettings': 'Dil Ayarları',
    'turkish': 'Türkçe',
    'english': 'İngilizce',
    'settings': 'Ayarlar',
    'darkMode': 'Karanlık Mod',
    'lightMode': 'Aydınlık Mod',
    'twitterLikeApp': 'Twitter Benzeri',
    'news': 'Haberler',
    'no_news_found': 'Haber bulunamadı.',
    'error_fetching_news': 'Haberleri çekerken hata oluştu.',
    'retry': 'Tekrar Dene',
    'news_app_title': 'Haber Uygulaması',
    'select_language': 'Dili Seçin',
    'theme': 'Tema',
    'editProfile': 'Profili Düzenle',
    'name': 'Ad',
    'email': 'E-posta',
    'bio': 'Biyografi',
    'save': 'Kaydet',
    'profilePicture': 'Profil Fotoğrafı URL',
    'requiredField': 'Bu alan boş bırakılamaz!',
    'invalidEmail': 'Geçerli bir e-posta adresi giriniz!',
    'profileUpdated': 'Profil başarıyla güncellendi!',
    'chooseFromGallery': 'Galeriden Seç',
    'takePhoto': 'Fotoğraf Çek',
    'photoUpdated': 'Fotoğraf Güncellendi',
    'football': 'Futbol',
    'fixtures': 'Fikstür',
    'noFixtures': 'Fikstür bulunamadı.',
    'matchNotPlayed': 'Maç Henüz Oynanmadı',
    'searchMatch': 'Maç Ara...',
    'standings': 'Puan Durumu',
    'noStandings': 'Puan durumu bulunamadı.',
    'topScorers': 'Gol Krallığı',
    'noTopScorers': 'Gol krallığı bulunamadı.',
    'errorLoadingStandings': 'Puan durumu yüklenirken hata oluştu.',
    'errorLoadingTopScorers': 'Gol krallığı yüklenirken hata oluştu.',
    'leagues': 'Ligler',
    'rank': 'Sıra',
    'team': 'Takım',
    'played': 'O',
    'won': 'G',
    'lost': 'M',
    'points': 'P',
    // Lig isimleri için eşleştirme (manuel çeviri):
    'Trendyol Süper Lig': 'Trendyol Super League',
    'Trendyol 1. Lig': 'Trendyol 1st League',
    'İngiltere Premier Ligi': 'English Premier League',
    'UEFA Konferans Ligi': 'UEFA Conference League',
    'Almanya Bundesliga': 'Germany Bundesliga',
    'Fransa Ligue 1': 'France Ligue 1',
    'İspanya La Liga': 'Spain La Liga',
    'İtalya Serie A': 'Italy Serie A',
    'İngiltere Championship': 'England Championship',
    'Almanya 2. Bundesliga': 'Germany 2. Bundesliga',
    'Fransa Ligue 2': 'France Ligue 2',
    'Avrupa Şampiyonası': 'European Championship',
    'beINsquad': 'beINsquad',
    'Türkiye Sigorta Basketbol Süper Ligi':
        'Türkiye Sigorta Basketball Super League',
    'Turkish Airlines EuroLeague': 'Turkish Airlines EuroLeague',
    'NBA': 'NBA',
    'Voleybol': 'Volleyball',
    'Güreş': 'Wrestle',
    'Atletizm': 'Athletics',
    'e-Spor': 'e-Sports',
    'Diğer Sporlar': 'Other Sports',
    // Özetler kısmı (lig özetleri)
    'Trendyol Süper Lig Özetler': 'Trendyol Super League Highlights',
    'Trendyol Süper Lig Goller': 'Trendyol Super League Goals',
    'Trendyol 1. Lig Özetler': 'Trendyol 1st League Highlights',
    'İngiltere Premier Lig Özetler': 'English Premier League Highlights',
    'Almanya Bundesliga Özetler': 'Germany Bundesliga Highlights',
    'Fransa Ligue 1 Özetler': 'France Ligue 1 Highlights',
    'Almanya 2. Bundesliga Özetler': 'Germany 2. Bundesliga Highlights',
    'Fransa Ligue 2 Özetler': 'France Ligue 2 Highlights',
    'Türkiye Sigorta Basketbol Süper Ligi Özetler':
        'Türkiye Sigorta Basketball Super League Highlights',
    'sports': 'Spor',
    'art': 'Sanat',
    'movies': 'Filmler',
    'series': 'Diziler',
    'theater': 'Tiyatro',
    'movies_in_cinemas': 'Vizyondakiler',
    'movies_coming_soon': 'Gelecekte Girecekler',
    'no_data_found': 'Veri bulunamadı',
    'release_date': 'Vizyon Tarihi',
    'rating_label': 'Puan',
    'close_label': 'Kapat',
    'now_playing': 'Vizyonda ',
    'top_rated': 'En Yüksek Oy',
    'favorites': 'Favoriler',
    'on_air': 'Yayında',
    'movie_subtitle': 'Film verileri gösterir',
    'series_subtitle': 'Dizi verileri gösterir',
    'theater_subtitle': 'Şu an oynanan tiyatro oyunlarını gösterir',
    'sahne': 'Sahne',
    'business_hours': 'Çalışma Saatleri',
    'view_menu': 'Menüyü Görüntüle',
    'search_hint': 'Ara...',
    'add_to_favorites': 'Favorilere Ekle',
    'open_now': 'Açık',
    'food': 'Yemek',
    'closed': 'Kapalı',
    'categories': 'Kategoriler',
    'monday': 'Pazartesi',
    'tuesday': 'Salı',
    'wednesday': 'Çarşamba',
    'thursday': 'Perşembe',
    'friday': 'Cuma',
    'saturday': 'Cumartesi',
    'sunday': 'Pazar',
    'HobbyHub': 'HobbyHub',
  };

  static Map<String, String> en = {
    'view_menu': 'View Menu',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'categories': 'Categories',
    'business_hours': 'Business Hours',
    'food': 'Food',
    'closed': 'Closed',
    'open_now': 'Open Now',
    'add_to_favorites': 'Add to Favorites',
    'sahne': 'Stage',
    'theater_subtitle': 'Shows current theater plays',
    'series_subtitle': 'Shows series data',
    'movie_subtitle': 'Shows movie data',
    'series': 'Series',
    'on_air': 'On Air',
    'top_rated': 'Top Rated',
    'favorites': 'Favorites',
    'no_data_found': 'No Data Found',
    'search_hint': 'Search...',
    'release_date': 'Release Date',
    'rating_label': 'Rating',

    'now_playing': 'Now Playing',

    'close_label': 'Close',
    'HobbyHub': 'HobbyHub',

    'movies': 'Movies',
    'movies_in_cinemas': 'Now Playing',
    'movies_coming_soon': 'Coming Soon',
    'search': 'Search',
    'notifications': 'Notifications',
    'home': 'Home',
    'messages': 'Messages',
    'profile': 'Profile',
    'languageSettings': 'Language Settings',
    'turkish': 'Turkish',
    'english': 'English',
    'settings': 'Settings',
    'darkMode': 'Dark Mode',
    'lightMode': 'Light Mode',
    'twitterLikeApp': 'Twitter-like App',
    'news': 'News',
    'no_news_found': 'No news found.',
    'error_fetching_news': 'An error occurred while fetching news.',
    'retry': 'Retry',
    'news_app_title': 'News App',
    'select_language': 'Select Language',
    'theme': 'Theme',
    'editProfile': 'Edit Profile',
    'name': 'Name',
    'email': 'Email',
    'bio': 'Bio',
    'save': 'Save',
    'profilePicture': 'Profile Picture URL',
    'requiredField': 'This field cannot be empty!',
    'invalidEmail': 'Please enter a valid email address!',
    'profileUpdated': 'Profile updated successfully!',
    'chooseFromGallery': 'Choose from Gallery',
    'takePhoto': 'Take a Photo',
    'photoUpdated': 'Photo Updated',
    'football': 'Football',
    'fixtures': 'Fixtures',
    'noFixtures': 'No fixtures found.',
    'matchNotPlayed': 'Match not played yet',
    'searchMatch': 'Search match...',
    'standings': 'Standings',
    'noStandings': 'No standings found.',
    'topScorers': 'Top Scorers',
    'noTopScorers': 'No top scorers found.',
    'errorLoadingStandings': 'Error loading standings.',
    'errorLoadingTopScorers': 'Error loading top scorers.',
    'leagues': 'Leagues',
    'rank': 'Rank',
    'team': 'Team',
    'played': 'P',
    'won': 'W',
    'lost': 'L',
    'points': 'Pts',
    'Trendyol Süper Lig': 'Trendyol Super League',
    'Trendyol 1. Lig': 'Trendyol 1st League',
    'İngiltere Premier Ligi': 'English Premier League',
    'UEFA Konferans Ligi': 'UEFA Conference League',
    'Almanya Bundesliga': 'Germany Bundesliga',
    'Fransa Ligue 1': 'France Ligue 1',
    'İspanya La Liga': 'Spain La Liga',
    'İtalya Serie A': 'Italy Serie A',
    'İngiltere Championship': 'England Championship',
    'Almanya 2. Bundesliga': 'Germany 2. Bundesliga',
    'Fransa Ligue 2': 'France Ligue 2',
    'Avrupa Şampiyonası': 'European Championship',
    'beINsquad': 'beINsquad',
    'Türkiye Sigorta Basketbol Süper Ligi':
        'Türkiye Sigorta Basketball Super League',
    'Turkish Airlines EuroLeague': 'Turkish Airlines EuroLeague',
    'NBA': 'NBA',
    'Voleybol': 'Volleyball',
    'Güreş': 'Wrestle',
    'Atletizm': 'Athletics',
    'e-Spor': 'e-Sports',
    'Diğer Sporlar': 'Other Sports',
    'sports': 'Sports',
    // Özetler kısmı
    'Trendyol Süper Lig Özetler': 'Trendyol Super League Highlights',
    'Trendyol Süper Lig Goller': 'Trendyol Super League Goals',
    'Trendyol 1. Lig Özetler': 'Trendyol 1st League Highlights',
    'İngiltere Premier Lig Özetler': 'English Premier League Highlights',
    'Almanya Bundesliga Özetler': 'Germany Bundesliga Highlights',
    'Fransa Ligue 1 Özetler': 'France Ligue 1 Highlights',
    'Almanya 2. Bundesliga Özetler': 'Germany 2. Bundesliga Highlights',
    'Fransa Ligue 2 Özetler': 'France Ligue 2 Highlights',
    'Türkiye Sigorta Basketbol Süper Ligi Özetler':
        'Türkiye Sigorta Basketball Super League Highlights',
    'art': 'Art',

    'theater': 'Theater',
  };

  // Haber kaynaklarının Türkçe isimlerini tanımlayan harita
  static Map<String, String> sourceNamesTr = {
    'sabah': 'Sabah',
    'cumhuriyet': 'Cumhuriyet',
    'hurriyet': 'Hürriyet',
    'karar': 'Karar',
    'habertürk': 'HaberTürk',
    // Diğer kaynaklar...
    'bbc-news': 'BBC Haber',
    'cnn': 'CNN Haber',
    'al-jazeera-english': 'Al Jazeera İngilizce',
    // Ek kaynakları buraya ekleyin
  };

  // Basit bir yardımcı fonksiyon:
  static String getText(String langCode, String key) {
    if (langCode == 'tr') {
      return tr[key] ?? key;
    } else {
      return en[key] ?? key;
    }
  }

  // Source ID'den Türkçe kaynak ismini al
  static String getSourceNameTr(String sourceId) {
    return sourceNamesTr[sourceId.toLowerCase()] ?? 'Kaynak';
  }
}
